import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const clientsData = [
  {
    codigo: "HHT-CRM-001",
    empresa: "ALMACENES BOCANEGRA S.A.(3 COTIZACIONES)",
    ruc: "20101415831",
    tarifa: "MT3",
    contacto: "Stephen",
    telefono: "",
    asignadoA: "Valentina",
    proximoSeguimiento: "2026-06-03T12:00:00Z",
    ultimoContacto: "2026-06-01T12:00:00Z",
    tipoCliente: "Fidelizado",
    prioridad: "Alta",
    direccion: "Carr. Piura - Sullana Nº 1010.5 Z.Ind. zona industrial",
    zona: "Zona Industrial",
    estado: "Activo",
    etapaComercial: "Seguimiento",
    semaforo: "Verde",
    temperatura: "Caliente",
    accion: "Seguimiento de cotizaciones"
  },
  {
    codigo: "HHT-CRM-002",
    empresa: "MAYORSA S.A",
    ruc: "20108730294",
    tarifa: "MT3",
    contacto: "Mario Rasilla",
    telefono: "996373910",
    asignadoA: "Valentina",
    proximoSeguimiento: "2026-06-03T12:00:00Z",
    ultimoContacto: "2026-06-01T12:00:00Z",
    tipoCliente: "Fidelizado",
    prioridad: "Alta",
    direccion: "Urbanizacion Santa Isabel Piura",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Seguimiento",
    semaforo: "Verde",
    temperatura: "Caliente",
    accion: "Llamada de seguimiento"
  },
  {
    codigo: "HHT-CRM-003",
    empresa: "DIARIO EL TIEMPO",
    ruc: "20102505957",
    tarifa: "MT3",
    contacto: "ELENA PINGO",
    telefono: "969696597",
    asignadoA: "Valentina",
    proximoSeguimiento: "2026-06-05T12:00:00Z",
    ultimoContacto: "2026-05-31T12:00:00Z",
    tipoCliente: "Secundario",
    prioridad: "Media",
    direccion: "ZONA INDUSTRIAL PIURA",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Amarillo",
    temperatura: "Tibio",
    accion: "Contacto inicial"
  },
  {
    codigo: "HHT-CRM-004",
    empresa: "FRUITXCHANGE",
    ruc: "20526145543",
    tarifa: "MT3",
    contacto: "GERMAN ARENAS",
    telefono: "976389933",
    asignadoA: "Valentina",
    proximoSeguimiento: "2026-06-03T12:00:00Z",
    ultimoContacto: "2026-05-31T12:00:00Z",
    tipoCliente: "Nuevo",
    prioridad: "Alta",
    direccion: "SULLANA",
    zona: "Sullana",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Caliente",
    accion: "Presentación de servicios"
  },
  {
    codigo: "HHT-CRM-005",
    empresa: "IPESA",
    ruc: "20101639275",
    tarifa: "MT3",
    contacto: "ANDRES VALERA",
    telefono: "976457032",
    asignadoA: "Valentina",
    proximoSeguimiento: "2026-06-04T12:00:00Z",
    ultimoContacto: "2026-06-01T12:00:00Z",
    tipoCliente: "Recurrente",
    prioridad: "Alta",
    direccion: "PIURA AV SANCHEZ CERRO",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Seguimiento",
    semaforo: "Verde",
    temperatura: "Caliente",
    accion: "Llamada de mantenimiento"
  },
  {
    codigo: "HHT-CRM-006",
    empresa: "IMPEMAR",
    ruc: "20509983985",
    tarifa: "MT3",
    contacto: "PEDRO LACHIRA",
    telefono: "937706009",
    asignadoA: "Valentina",
    proximoSeguimiento: null,
    ultimoContacto: "2026-05-23T12:00:00Z",
    tipoCliente: "Recurrente",
    prioridad: "Alta",
    direccion: "CARR PIURA SULLANA",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Amarillo",
    temperatura: "Tibio",
    accion: "Pendiente cotización"
  },
  {
    codigo: "HHT-CRM-007",
    empresa: "PRODUSERVIS",
    ruc: "20559824578",
    tarifa: "MT3",
    contacto: "MARITZA SOSA",
    telefono: "968937188",
    asignadoA: "Valentina",
    proximoSeguimiento: "2026-06-04T12:00:00Z",
    ultimoContacto: "2026-05-26T12:00:00Z",
    tipoCliente: "Nuevo",
    prioridad: "Alta",
    direccion: "PIURA FUTURA",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Caliente",
    accion: "Contacto comercial"
  },
  {
    codigo: "HHT-CRM-008",
    empresa: "COOPERATIVA AGRARIA NOR ANDINO",
    ruc: "2052416543",
    tarifa: "MT3",
    contacto: "—",
    telefono: "",
    asignadoA: "Angi",
    proximoSeguimiento: null,
    ultimoContacto: null,
    tipoCliente: "Nuevo",
    prioridad: "Media",
    direccion: "Piura",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Tibio",
    accion: "Por contactar"
  },
  {
    codigo: "HHT-CRM-009",
    empresa: "MOCHIGOMI",
    ruc: "20602908292",
    tarifa: "MT3",
    contacto: "—",
    telefono: "",
    asignadoA: "Angi",
    proximoSeguimiento: null,
    ultimoContacto: null,
    tipoCliente: "Nuevo",
    prioridad: "Media",
    direccion: "Piura",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Tibio",
    accion: "Por contactar"
  },
  {
    codigo: "HHT-CRM-010",
    empresa: "TALLANES PACKERS S.A.C",
    ruc: "20999999999", // Temp RUC as it's missing
    tarifa: "MT3",
    contacto: "—",
    telefono: "",
    asignadoA: "Angi",
    proximoSeguimiento: null,
    ultimoContacto: null,
    tipoCliente: "Nuevo",
    prioridad: "Media",
    direccion: "Piura",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Tibio",
    accion: "Por contactar"
  },
  {
    codigo: "HHT-CRM-011",
    empresa: "DISTRIBUIDORA COMERCIAL ALVAREZ BOHL",
    ruc: "20102892381",
    tarifa: "MT3",
    contacto: "ANDRES GUIDINO",
    telefono: "998196776",
    asignadoA: "Valentina",
    proximoSeguimiento: "2026-06-03T12:00:00Z",
    ultimoContacto: "2026-05-25T12:00:00Z",
    tipoCliente: "Recurrente",
    prioridad: "Alta",
    direccion: "CARR PIURA SULLANA",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Amarillo",
    temperatura: "Tibio",
    accion: "Seguimiento periódico"
  },
  {
    codigo: "HHT-CRM-012",
    empresa: "SEAFROST",
    ruc: "20888888888", // Temp RUC as it's missing
    tarifa: "MT3",
    contacto: "—",
    telefono: "",
    asignadoA: "Angi",
    proximoSeguimiento: null,
    ultimoContacto: null,
    tipoCliente: "Nuevo",
    prioridad: "Media",
    direccion: "Piura",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Tibio",
    accion: "Por contactar"
  },
  {
    codigo: "HHT-CRM-013",
    empresa: "AMARA FOODS SAC",
    ruc: "20777777777", // Temp RUC as it's missing
    tarifa: "MT3",
    contacto: "—",
    telefono: "",
    asignadoA: "Angi",
    proximoSeguimiento: null,
    ultimoContacto: null,
    tipoCliente: "Nuevo",
    prioridad: "Media",
    direccion: "Piura",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Tibio",
    accion: "Por contactar"
  },
  {
    codigo: "HHT-CRM-014",
    empresa: "SIPAN",
    ruc: "20666666666", // Temp RUC as it's missing
    tarifa: "MT3",
    contacto: "—",
    telefono: "",
    asignadoA: "Angi",
    proximoSeguimiento: null,
    ultimoContacto: null,
    tipoCliente: "Nuevo",
    prioridad: "Media",
    direccion: "Piura",
    zona: "Piura",
    estado: "Activo",
    etapaComercial: "Prospecto",
    semaforo: "Verde",
    temperatura: "Tibio",
    accion: "Por contactar"
  }
];

async function main() {
  console.log('Inserting clients...');
  for (const client of clientsData) {
    try {
      await prisma.cliente.upsert({
        where: { ruc: client.ruc },
        update: client,
        create: client,
      });
      console.log(`Success: ${client.empresa}`);
    } catch (e) {
      console.error(`Error inserting ${client.empresa}:`, e.message);
    }
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
